# Generated by Django 3.2.12 on 2022-03-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('animal', models.CharField(max_length=64)),
                ('food', models.CharField(max_length=64)),
                ('things', models.CharField(max_length=64)),
            ],
        ),
    ]
