# Generated by Django 3.2.12 on 2022-04-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
